### ISSUE TITLE
Error: Cannot Assign Outlook Filters

### ISSUE THREAD

**Issue by ckilcullen** [MscrmTools/MscrmTools.SyncFilterManager#2]
When I try to apply my Synchronization Filter Template to my users I get the error "Error while applying filters to users: Cannot assign Outlook filters. Does anyone have any insight in to what I could be doing wrong?

Thanks
![xrm toolbox error](https://user-images.githubusercontent.com/37915992/38116627-eeb51fd2-337e-11e8-913d-1eccf0d0ea11.JPG)
!

**Comment by pokkemonner** [comment]
Same here. I am SystemAdministrator

**Comment by jellevervloessem** [comment]
+1 here the same.
