### ISSUE TITLE
I am attempting to apply a user filter to other users.  Getting this error - not sure why - any idaas?

### ISSUE THREAD

**Issue by surfmaverick** [MscrmTools/MscrmTools.SyncFilterManager#5]
<img width="754" alt="Screen Shot 2020-08-17 at 10 30 40 PM" src="https://user-images.githubusercontent.com/3749975/90467244-506bf980-e0d9-11ea-82d8-6b64786da091.png">

**Comment by adam-murabito** [comment]
I'm receiving the same error when attempting to apply a user's filters to another user. I followed Mark's suggestion to clear the cache on [this similar-looking issue](https://github.com/MscrmTools/XrmToolBox/issues/1052), but I'm still receiving the error. It's happening in online orgs only, on-premises seems unaffected. @MscrmTools, can you please help?

**Comment by MscrmTools** [comment]
This version should fix the issue. Can you test it and confirm?

[MscrmTools.SyncFilterManager.zip](https://github.com/MscrmTools/MscrmTools.SyncFilterManager/files/6821126/MscrmTools.SyncFilterManager.zip)

**Comment by adam-murabito** [comment]
@MscrmTools - The new version appears to have fixed the issue. I can successfully apply a user's filter to another user in an online org. Thank you for the quick turnaround!
