### ISSUE TITLE
New feature for Outlook Sync Filter

### ISSUE THREAD

**Issue by LehmReyDE** [MscrmTools/MscrmTools.SyncFilterManager#6]
Is there any chance to create a new Outlook filter as systemview?

I need it to deploy a new version of Contact Sync rule.

**Comment by MscrmTools** [comment]
Not sure to understand the question

**Comment by MscrmTools** [comment]
@LehmReyDE, If you go to System Views tab, you can create a new Outlook filter from one of the system view.

**Comment by LehmReyDE** [comment]
Hi I've checked but I can't find any option to create a new Outlook view for Synchronizing in the Customizing.
I checked it in the legacy and in maker Portal. 

I can create a new View for my own user, but this is not the case.

**Comment by MscrmTools** [comment]
Just create a normal system view, and use it in this tool to create an Outlook View from this new sytem view

**Comment by LehmReyDE** [comment]
Ok Sorry, now I see the button, I search for it but I can't find the Tree in front of the wood
