### ISSUE TITLE
Privilege error when assign filter to user but no details

### ISSUE THREAD

**Issue by D365CEAdmin** [MscrmTools/MscrmTools.SyncFilterManager#7]
Hello! I am trying to assign a filter to a series of users but I'm getting the following error:

![2022-01-18_16-46-33](https://user-images.githubusercontent.com/97992208/150028480-87a94fdc-9d94-4395-b792-02b308f69d7f.png)

It's not telling me which entity privileges are missing so troubleshooting is a challenge. The first GIUD is the user to which I'm trying to apply the filter but the other ones are not and they don't match the GUIDs of the security roles. These are non-admin users but, as a test, I added the system admin role to user and then the filter would apply. 

Any thoughts?

**Comment by MscrmTools** [comment]
Thé missing privilege is mentioned. It's prvAdminFilter.
I guess this is a privilege a user must have so that it is possible to manage sync filters.

**Comment by dkasp** [comment]
So I had the same issue today despite the user I'm connecting with being a sysadmin.
I've taken a look into the source and it seems like ApplyRulesToUser() is the function being used for this, and that function replaces the logged in user with the target user for the sync filter update for the Execute() that processes the InstantiateFiltersRequests - when I simply removed the three lines responsible for that, it fixed the issue.

RulesManager.cs:L84            ((CrmServiceClient)service).CallerId = userId; <- this causes the issue apparently
there're two more lines where the previous CallerId is temporarily stored and restored to the service, these should be unneccessary once L84 is removed (i've removed all three lines without causing new issues)

**Comment by MscrmTools** [comment]
Maybe something have changed but when this tool was created, I had to impersonate as the user to apply rules to that user

So you confirm, it's not necessary anymore?

**Comment by dkasp** [comment]
yeah, I'm pretty sure something was changed on CRM side. For me it works without impersonating now.
