### ISSUE TITLE
Error when copying a user filter to another user in v 1.2022.3.4

### ISSUE THREAD

**Issue by olivergraf80** [MscrmTools/MscrmTools.SyncFilterManager#8]
When using the current version of the XrmToolBox 1.2022.4.55 in combination with the SyncFilterManager 1.2022.3.4 an error occurs when trying to copy user sync filters from one user to another.
steps for reproduction:
 - go to tab "Users"
 - search for a specific user
 - select the user
 - click on "apply selected user synchronization filter to user(s)
 - a popup opens where i can search for a target user.
 - having a target user selected and clicking okay an error message appears: "Error while applying filters".
 
![error_while_applying](https://user-images.githubusercontent.com/105229749/167447781-05c1c3e8-01b7-43e9-b7f0-e8e3bda3e0b8.png)

**Comment by olivergraf80** [comment]
P.S.: in older versions of XrmToolbox in combination e.g. with the 2021 version of the syncfilter manager it is working

**Comment by MscrmTools** [comment]
@olivergraf80  Can you test with this version ?
[MscrmTools.SyncFilterManager.zip](https://github.com/MscrmTools/MscrmTools.SyncFilterManager/files/8706081/MscrmTools.SyncFilterManager.zip)

**Comment by Painy187** [comment]
Also had the same issue and tested with this release. It works fine. Thanks!

**Comment by olivergraf80** [comment]
Thanks!

**Comment by mc-jonathan** [comment]
> @olivergraf80 Can you test with this version ? [MscrmTools.SyncFilterManager.zip](https://github.com/MscrmTools/MscrmTools.SyncFilterManager/files/8706081/MscrmTools.SyncFilterManager.zip)

It fixed the issue for me. Thanks!

**Comment by MscrmTools** [comment]
Thank you, I will push a new release then
